### ISSUE TITLE
PHP leftovers?!

### ISSUE THREAD

**Issue by romaincointepas** [ProcessOut/processout-python#6]
`tmp = Event($this->instance)`

https://github.com/ProcessOut/processout-python/blob/master/processout/customer.py#L286

https://github.com/ProcessOut/processout-python/search?utf8=%E2%9C%93&q=this-%3E&type=Code

**Comment by manuel-huez** [comment]
The leftovers were due to the way the library is automatically generated based on the API specifications.
This is now fixed!
