### ISSUE TITLE
Support for python 2.7

### ISSUE THREAD

**Issue by romaincointepas** [ProcessOut/processout-python#7]
Python 3 **ONLY** seems a bit harsh :) (Also, it means no AppEngine support)

Ex:
`from urllib.parse import quote_plus` (python 3) -> `from urllib import quote_plus` (python 2.7)

**Comment by manuel-huez** [comment]
https://github.com/ProcessOut/processout-python/releases/tag/3.2.0.0
Aims to increase support to python 2.7.

**Comment by manuel-huez** [comment]
Feedback from @LouisBorlee confirms that version `3.2.0.0` supports Python 2.7.
