### ISSUE TITLE
Circular imports everywhere

### ISSUE THREAD

**Issue by romaincointepas** [ProcessOut/processout-python#8]
Basically `ImportError: cannot import name CustomerAction`-type exceptions thrown. (Added bonus is that each dependency is also importing itself).

The entire lib is pretty much unusable without a dependency refactor (at least on python 2.7. It's weird that it works on python 3 as it's considered bad design for python).

**Comment by manuel-huez** [comment]
Fixed with https://github.com/ProcessOut/processout-python/commit/120fa92ad0132d818dcf312c8365dee5385a39ae
